---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: zitadel-gateway
  namespace: zitadel
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: auth.corruptmane.xyz
      tls:
        mode: Terminate
        certificateRefs:
          - name: zitadel-tls
