---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: /homelab/grafana-oidc-client-id
    - secretKey: client-secret
      remoteRef:
        key: /homelab/grafana-oidc-client-secret
