---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: pihole-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /homelab/pihole-password
