---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-master-key
  namespace: zitadel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: zitadel-master-key
    creationPolicy: Owner
  data:
    - secretKey: masterkey
      remoteRef:
        key: /homelab/zitadel-master-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-admin-password
  namespace: zitadel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: zitadel-admin-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /homelab/zitadel-admin-password
