---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/helmrepository.yaml
  - cilium/helmrelease.yaml

  - cert-manager/namespace.yaml
  - cert-manager/helmrepository.yaml
  - cert-manager/helmrelease.yaml

  - external-secrets/helmrepository.yaml
  - external-secrets/helmrelease.yaml

  - external-dns/namespace.yaml
  - external-dns/external-secret.yaml
  - external-dns/helmrepository.yaml
  - external-dns/helmrelease.yaml

  - kyverno/namespace.yaml
  - kyverno/helmrepository.yaml
  - kyverno/helmrelease.yaml

  - longhorn/namespace.yaml
  - longhorn/helmrepository.yaml
  - longhorn/helmrelease.yaml
