---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-credentials
            namespace: external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-ssm-credentials
            namespace: external-secrets
            key: secret-access-key
