---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: "10.5.15"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicas: 1

    persistence:
      enabled: false

    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
        secretKeyRef:
          name: grafana-oidc
          key: client-id
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-oidc
          key: client-secret
    grafana.ini:
      server:
        root_url: https://grafana.corruptmane.xyz
      auth:
        disable_login_form: false
      auth.generic_oauth:
        enabled: true
        name: Zitadel
        allow_sign_up: true
        scopes: openid profile email
        auth_url: https://auth.corruptmane.xyz/oauth/v2/authorize
        token_url: https://auth.corruptmane.xyz/oauth/v2/token
        api_url: https://auth.corruptmane.xyz/oidc/v1/userinfo
        use_pkce: true
        # TODO: switch to proper RBAC using Zitadel project roles
        skip_org_role_sync: false
      users:
        auto_assign_org_role: Admin

    plugins:
      - victoriametrics-metrics-datasource
      - victoriametrics-logs-datasource

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: victoriametrics-metrics-datasource
            url: http://vmsingle-victoria-metrics-victoria-metrics-k8s-stack:8428
            access: proxy
            isDefault: true
          - name: VictoriaLogs
            type: victoriametrics-logs-datasource
            url: http://victoria-logs-victoria-logs-single-server:9428
            access: proxy
          - name: VictoriaTraces
            type: tempo
            url: http://victoria-traces-vt-single-server:10428/vt
            access: proxy

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
