---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zitadel/certificate.yaml
  - zitadel/gateway.yaml
  - zitadel/httproute.yaml
  - zitadel/helmrelease.yaml

  - grafana/certificate.yaml
  - grafana/gateway.yaml
  - grafana/httproute.yaml
  - grafana/helmrelease.yaml

  - ntfy/external-secret.yaml
  - ntfy/pvc.yaml
  - ntfy/deployment.yaml
  - ntfy/service.yaml
  - ntfy/certificate.yaml
  - ntfy/gateway.yaml
  - ntfy/httproute.yaml
